name: 'Lint with StandardJS'
description: 'Lint your JavaScript and Node.js projects with StandardJS'
author: 'Tierney Cyren (GitHub: @bnb / Twitter: @bitandbang)'
inputs:
  standard-version:
    description: 'The version of StandardJS to use. Defaults to `latest`.'
    default: 'latest'
runs:
  using: 'node12'
  main: 'lib/main.js'